
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 15 15:53:50 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int CASE = 18;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 42;
  public static final int SEMI = 39;
  public static final int GREATER = 30;
  public static final int CONTINUE = 17;
  public static final int DECR = 38;
  public static final int INCR = 37;
  public static final int LESS = 32;
  public static final int MINUS = 24;
  public static final int RPAREN = 43;
  public static final int CHARACTER = 20;
  public static final int AND = 34;
  public static final int RELEQUAL = 28;
  public static final int OR = 35;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int LESSEQ = 33;
  public static final int IF = 7;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 21;
  public static final int RETURN = 14;
  public static final int EQUAL = 36;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int NUMBER = 19;
  public static final int MOD = 27;
  public static final int BREAK = 3;
  public static final int IDENT = 22;
  public static final int VOID = 15;
  public static final int SWITCH = 8;
  public static final int COLON = 49;
  public static final int LBRACE = 44;
  public static final int ELSE = 5;
  public static final int LSQUARE = 46;
  public static final int READ = 13;
  public static final int RSQUARE = 47;
  public static final int WHILE = 10;
  public static final int RBRACE = 45;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int QUESTION = 48;
  public static final int GREATEREQ = 31;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

