
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 04 19:34:57 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int NOTEQUAL = 26;
  public static final int LPAREN = 39;
  public static final int SEMI = 36;
  public static final int GREATER = 27;
  public static final int CONTINUE = 14;
  public static final int DECR = 35;
  public static final int INCR = 34;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int RPAREN = 40;
  public static final int CHARACTER = 17;
  public static final int AND = 31;
  public static final int RECORD = 47;
  public static final int RELEQUAL = 25;
  public static final int OR = 32;
  public static final int COMMA = 37;
  public static final int DIV = 22;
  public static final int PLUS = 20;
  public static final int LESSEQ = 30;
  public static final int IF = 4;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 12;
  public static final int EQUAL = 33;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int NUMBER = 16;
  public static final int MOD = 24;
  public static final int BREAK = 3;
  public static final int IDENT = 19;
  public static final int VOID = 13;
  public static final int COLON = 46;
  public static final int LBRACE = 41;
  public static final int ELSE = 5;
  public static final int LSQUARE = 43;
  public static final int READ = 11;
  public static final int GOTO = 15;
  public static final int RSQUARE = 44;
  public static final int WHILE = 8;
  public static final int RBRACE = 42;
  public static final int PROG = 2;
  public static final int QUESTION = 45;
  public static final int GREATEREQ = 28;
  public static final int PRINT = 10;
  public static final int DO = 7;
}

